name: recorder_summary
description: "Recorder summary."

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # icons
  cupertino_icons: ^1.0.6
  material_design_icons_flutter: ^7.0.7296
  font_awesome_flutter: ^10.7.0

  # image
  flutter_svg: ^2.0.10+1

  # message
  elegant_notification: ^2.1.2

  # onboarding
  carousel_slider: ^4.2.1

  # firebase
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  google_sign_in: ^6.2.1
  flutter_secure_storage: ^9.0.0

  # provider
  provider: ^6.1.2

  # launcher
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

  # url
  url_launcher: ^6.2.6

  # bottom navigation
  animated_notch_bottom_bar: ^1.0.3

  # record and play
  audio_waveforms: ^1.0.5
  just_audio: ^0.9.39

  # permission
  permission_handler: ^11.3.1

  # path
  path: ^1.9.0
  path_provider: ^2.1.3
  file_picker: ^8.0.3

  # dates
  intl: ^0.19.0

  # slider
  flutter_slidable: ^3.1.1

  # indicator
  loading_animation_widget: ^1.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

# icon launcher
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21

# splash screen
flutter_native_splash:
  color: "#180e2c"
  image: assets/logo_splash.png
  android: true
  ios: true
  web: false

  android_12:
    color: "#180e2c"
    image: assets/logo_splash.png

flutter:
  uses-material-design: true

  assets:
    - assets/
    
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Italic.ttf
          style: italic
        - asset: fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Poppins-Black.ttf
          weight: 900
        - asset: fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic