// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP07No6EpGFaNi3suGUmycXS2wLkOcfCY',
    appId: '1:977236790960:web:5d9a911fa087680af7b575',
    messagingSenderId: '977236790960',
    projectId: 'summary-recorder-969db',
    authDomain: 'summary-recorder-969db.firebaseapp.com',
    storageBucket: 'summary-recorder-969db.appspot.com',
    measurementId: 'G-DLCN5BZW64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtgxNT3MCmNJwh97J1QHOTv8bOPvZ6fSQ',
    appId: '1:977236790960:android:80994b18a1274f8cf7b575',
    messagingSenderId: '977236790960',
    projectId: 'summary-recorder-969db',
    storageBucket: 'summary-recorder-969db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKvmp0tWD4-h1aSVbpo9jAUieVo4GE8Oc',
    appId: '1:977236790960:ios:e40e0c36aa332036f7b575',
    messagingSenderId: '977236790960',
    projectId: 'summary-recorder-969db',
    storageBucket: 'summary-recorder-969db.appspot.com',
    iosClientId: '977236790960-3gn21cqvgrtpba4frgqgma6aif2vcacp.apps.googleusercontent.com',
    iosBundleId: 'com.example.recorderSummary',
  );
}
